from enum import IntEnum, unique


@unique
class DataAccessResult(IntEnum):
    SUCCESS = 0
    HARDWARE_FAULT = 1
    TEMPORARY_FAILURE = 2
    READ_WRITE_DENIED = 3
    OBJECT_UNDEFINED = 4
    OBJECT_CLASS_INCONSISTENT = 9
    OBJECT_UNAVAILABLE = 11
    TYPE_UNMATCHED = 12
    SCOPE_OF_ACCESS_VIOLATED = 13
    DATA_BLOCK_UNAVAILABLE = 14
    LONG_GET_ABORTED = 15
    NO_LONG_GET_IN_PROGRESS = 16
    LONG_SET_ABORTED = 17
    NO_LONG_SET_IN_PROGRESS = 18
    DATA_BLOCK_NUMBER_INVALID = 19
    OTHER_REASON = 250


class GetRequestType(IntEnum):
    NORMAL = 1
    NEXT = 2
    WITH_LIST = 3


class GetResponseType(IntEnum):
    NORMAL = 1
    WITH_BLOCK = 2
    WITH_LIST = 3


class SetRequestType(IntEnum):
    NORMAL = 1
    WITH_FIRST_BLOCK = 2
    WITH_BLOCK = 3
    WITH_LIST = 4
    FIRST_BLOCK_WITH_LIST = 5


class SetResponseType(IntEnum):
    NORMAL = 1
    WITH_BLOCK = 2
    WITH_LAST_BLOCK = 3
    LAST_BLOCK_WITH_LIST = 4
    WITH_LIST = 5


class ActionType(IntEnum):
    NORMAL = 1
    NEXT_PBLOCK = 2
    WITH_LIST = 3
    WITH_FIRST_PBLOCK = 4
    WITH_LIST_AND_FIRST_PBLOCK = 5
    WITH_PBLOCK = 6


class StateException(IntEnum):
    SERVICE_NOT_ALLOWED = 1
    SERVICE_UNKNOWN = 2


class ServiceException(IntEnum):
    OPERATION_NOT_POSSIBLE = 1
    SERVICE_NOT_SUPPORTED = 2
    OTHER_REASON = 3
    PDU_TOO_LONG = 4
    DECIPHERING_ERROR = 5
    INVOCATION_COUNTER_ERROR = 6


class ApplicationReferenceError(IntEnum):
    OTHER = 0
    TIME_ELAPSED = 1  # timeout since request sent
    APPLICATION_UNREACHABLE = 2  # peer AEi not reachable
    APPLICATION_REFERENCE_INVALID = 3  # addressing problems
    APPLICATION_CONTEXT_UNSUPPORTED = 4  # incompatible application context
    PROVIDER_COMMUNICATION_ERROR = 5  # error in local or remote equipment
    DECIPHERING_ERROR = 6  # Error detected in deciphering function.


class HardwareResourceError(IntEnum):
    OTHER = 0
    MEMORY_UNAVAILABLE = 1
    PROCESSOR_RESOURCE_UNAVAILABLE = 2
    MASS_STORAGE_UNAVAILABLE = 3
    OTHER_RESOURCE_UNAVAILABLE = 4


class VdeStateError(IntEnum):
    OTHER = 0
    NO_DLMS_CONTEXT = 1
    LOADING_DATASET = 2
    STATUS_NO_CHANGE = 3
    STATUS_INOPERABLE = 4


class ServiceError(IntEnum):
    OTHER = 0
    PDU_SIZE = 1  # PDU too long
    SERVICE_UNSUPPORTED = 2  # Service unsupported as in conformance block


class DefinitionError(IntEnum):
    OTHER = 0
    OBJECT_UNDEFINED = 1  # object not defined at the VDE
    OBJECT_CLASS_INCONSISTENT = 2  # class of object incompatible with asked service
    OBJECT_ATTRIBUTE_INCONSISTENT = 3  # object attributes are inconsistent to doc


class AccessError(IntEnum):
    OTHER = 0
    SCOPE_OF_ACCESS_VIOLATED = 1  # access denied through authorisation reason
    OBJECT_ACCESS_VIOLATED = 2  # access incompatible with object attribute
    HARDWARE_FAULT = 3  # access fail for hardware reasons
    OBJECT_UNAVAILABLE = 4  # VDE hands object for unavailable


class InitiateError(IntEnum):
    OTHER = 0
    DLMS_VERSION_TOO_LOW = 1  # proposed dlms version is too low
    INCOMPATIBLE_CONFORMANCE = 2  # proposed service not sufficient
    PDU_SIZE_TOO_SHORT = 3  # proposed pdu size is too short
    REFUSED_BY_VDE_HANDLER = 4  # vaa creation impossible or not allowed


class LoadDataError(IntEnum):
    OTHER = 0
    PRIMITIVE_OUT_OF_SEQUENCE = 1
    NOT_LOADABLE = 2
    DATASET_SIZE_TOO_LARGE = 3
    NOT_AWAITED_SEGMENT = 4
    INTERPRETATION_FAILURE = 5
    STORAGE_FAILURE = 6
    DATASET_NOT_READY = 7


class DataScopeError(IntEnum):
    OTHER = 0


class TaskError(IntEnum):
    OTHER = 0
    NO_REMOTE_CONTROL = 1
    TI_STOPPED = 2
    TI_RUNNING = 3
    TI_UNUSABLE = 4


class OtherError(IntEnum):
    OTHER = 0


@unique
class CosemInterface(IntEnum):

    # Parameters and measurement data (Blue Book standard)
    DATA = 1
    REGISTER = 2
    EXTENDED_REGISTER = 3
    DEMAND_REGISTER = 4
    PROFILE_GENERIC = 5
    CLOCK = 6
    SCRIPT_TABLE = 7
    SPECIAL_DAYS_TABLE = 8
    SCHEDULE = 9
    ASSOCIATION_SN = 10
    ASSOCIATION_LN = 11
    DEMAND = 12
    REGISTER_MONITOR = 13
    REGISTER_ACTIVATION = 14
    PUSH_SETUP = 15
    DISCONNECT_CONTROL = 16
    LIMITER = 17
    ACTIVITY_CALENDAR = 18
    DAY_PROFILE = 19
    WEEK_PROFILE = 20
    TARIFF_SCHEDULE = 21
    ACCOUNT = 22
    IEC_HDLC_SETUP = 23
    MODEM_CONFIGURATION = 24
    MBUS_MASTER_PORT_SETUP = 25
    MBUS_CLIENT = 26
    GPRS_MODEM_SETUP = 27
    SMTP_SETUP = 28
    SECURITY_SETUP = 29
    VALUE_DISPLAY = 30
    LOCAL_DISPLAY = 31
    IEC_PUBLIC_KEY = 32
    COSEM_DATA_PROTECTION = 33
    MBUS_SLAVE_PORT_SETUP = 34
    IMAGE_TRANSFER = 35
    FIRMWARE_MANAGEMENT = 36
    MULTIPLIER = 37
    MULTIPLIER_SETUP = 38
    TCP_UDP_SETUP = 39
    IPV4_SETUP = 40
    IPV4_TCP_SETUP = 41
    IPV4_UDP_SETUP = 42
    IPV6_SETUP = 43
    IPV6_TCP_SETUP = 44
    PPP_SETUP = 45
    ZIGBEE_SETUP = 46
    WI_SUN_SETUP = 47
    AUTO_CONNECT = 48
    APPLICATION_CONTEXT = 49
    TRANSPORT = 50
    ROUTE = 51
    ROUTE_SETUP = 52
    SAP_ASSIGNMENT = 53
    STATUS_MAPPING = 55
    SUPPLY_DISABLING = 56
    SENSOR_MANAGER = 57
    ACTUATOR_SETUP = 58
    SENSOR = 59
    SENSOR_SETUP = 60
    ACTUATOR = 61
    COMPACT_DATA = 62
    STANDARD_READOUT = 63
    BILLING = 64
    TOKEN_GATEWAY = 65
    CREDIT = 66
    CHARGE = 67
    UTILITY_SUB_SCHEDULE = 68
    CLUSTER = 69
    CALENDAR = 70
    SINGLE_ACTION_SCHEDULE = 71
    SCHEDULED_ACTIVITY = 72
    CLOCK_CONTROL = 73
    DATA_LOGGER = 74
    DATA_STORAGE = 75
    EVENT_LOG = 76
    EVENT_LOGGER = 77
    FUNCTION_CONTROL = 78
    PARAMETER_MONITOR = 79
    QUALITY_OF_SERVICE = 80
    LIFT_MANAGEMENT = 81
    ARBITRATOR = 82
    MBUS_DIAGNOSTIC = 83
    MPL_DIAGNOSTIC = 84
    RPL_DIAGNOSTIC = 85
    WI_SUN_DIAGNOSTIC = 86
    NTP_SETUP = 87
    UPS = 88
    DIRECT_DISCONNECT = 89
    LOAD_PROFILE_SWITCH = 90
    SERIAL_PORT = 92
    HAN_SETUP = 93
    STATUS_DIAG = 94
    EXTENDED_PROFILE = 95
    MBUS_MASTER = 96
    GAS_FLOW = 97
    GAS_VALVE = 98
    WATER_FLOW = 99
    LP_SETUP = 100
    RS485_SETUP = 101
    INFRARED_SETUP = 102
    ETHERNET_SETUP = 103
    LTE_SETUP = 104
    TLS_SETUP = 105
    NBIOT_SETUP = 106
    LORAWAN_SETUP = 107
    POWER_QUALITY_MONITOR = 110
    HARMONIC_MONITOR = 111
    SAG_SWELL_MONITOR = 112
    HEAT_COST_ALLOCATOR = 113
    MEASUREMENT_DATA_MONITORING = 114
    COMMUNICATION_PORT_PROTECTION = 115
    IDENTITY = 116
    MAC_ADDRESS_SETUP = 117
    LOAD_PROFILE = 118
    VALUE_TABLE = 119
    ALARM_HANDLER = 120
    UTILITY_TABLES = 121
    LTE_MONITORING = 151
    ARRAY_MANAGER = 211
    # Extended IC classes (200+)
    ACTIVE_POWER_IMPORT = 200
    SINGLE_PHASE_IMPORT = 201
    SINGLE_PHASE_EXPORT = 202
    SINGLE_PHASE_MQ = 203
    SINGLE_PHASE = 204
    MAXIMUM_DEMAND = 205
    TOTAL = 207
    COMM_CONTROL = 210
    # PLC profiles (PRIME, G3-PLC, HS-PLC)
    G3_PLC_MAC_LAYER_COUNTERS = 194
    G3_PLC_MAC_SETUP = 91
    HS_PLC_IEC_12139_1_MAC_SETUP = 140
    HS_PLC_IEC_12139_1_CPAS_SETUP = 141
    HS_PLC_IEC_12139_1_IP_SSAS_SETUP = 142
    HS_PLC_IEC_12139_1_HDLC_SSAS_SETUP = 143
    # Zigbee
    # LPWAN
    SCHC_LPWAN = 126
    SCHC_LPWAN_DIAGNOSTICS = 127
    LORAWAN_DIAGNOSTICS = 129
    # IEC 14908 PLC
    IEC_14908_IDENTIFICATION = 130
    IEC_14908_PROTOCOL_SETUP = 131
    IEC_14908_PROTOCOL_STATUS = 132
    IEC_14908_DIAGNOSTICS = 133


# Backward compatibility aliases (legacy names mapping to Blue Book values)
CosemInterface.REGISTER_TABLE = CosemInterface.ACTUATOR
CosemInterface.PUSH = CosemInterface.PUSH_SETUP
CosemInterface.IEC_LOCAL_PORT_SETUP = CosemInterface.INFRARED_SETUP
CosemInterface.IEC_TWISTED_PAIR_SETUP = CosemInterface.RS485_SETUP
CosemInterface.AUTO_ANSWER = CosemInterface.SMTP_SETUP
CosemInterface.GSM_DIAGNOSTICS = CosemInterface.WI_SUN_SETUP

@unique
class ReleaseRequestReason(IntEnum):
    NORMAL = 0
    URGENT = 1
    USER_DEFINED = 30


@unique
class ReleaseResponseReason(IntEnum):
    NOT_FINISHED = 1


class AuthenticationMechanism(IntEnum):
    NONE = 0
    LLS = 1
    HLS = 2
    HLS_MD5 = 3  # Insecure. Don't use with new meters
    HLS_SHA1 = 4  # Insecure. Don't use with new meters
    HLS_GMAC = 5
    HLS_SHA256 = 6
    HLS_ECDSA = 7


class AcseServiceUserDiagnostics(IntEnum):
    NULL = 0
    NO_REASON_GIVEN = 1
    APPLICATION_CONTEXT_NAME_NOT_SUPPORTED = 2
    CALLING_AP_TITLE_NOT_RECOGNIZED = 3
    CALLING_AP_INVOCATION_IDENTIFIER_NOT_RECOGNIZED = 4
    CALLING_AE_QUALIFIER_NOT_RECOGNIZED = 5
    CALLING_AE_INVOCATION_IDENTIFIER_NOT_RECOGNIZED = 6
    CALLED_AP_TITLE_NOT_RECOGNIZED = 7
    CALLED_AP_INVOCATION_IDENTIFIER_NOT_RECOGNIZED = 8
    CALLED_AE_QUALIFIER_NOT_RECOGNIZED = 9
    CALLED_AE_INVOCATION_IDENTIFIER_NOT_RECOGNIZED = 10
    AUTHENTICATION_MECHANISM_NAME_NOT_RECOGNIZED = 11
    AUTHENTICATION_MECHANISM_NAME_REQUIRED = 12
    AUTHENTICATION_FAILED = 13
    AUTHENTICATION_REQUIRED = 14


class AcseServiceProviderDiagnostics(IntEnum):
    NO_COMMON_ACSE_VERSION = 2


class AssociationResult(IntEnum):
    ACCEPTED = 0
    REJECTED_PERMANENT = 1
    REJECTED_TRANSIENT = 2
    # TODO: What does transient rejection mean?


class ActionResultStatus(IntEnum):
    SUCCESS = 0
    HARDWARE_FAULT = 1
    TEMPORARY_FAILURE = 2
    READ_WRITE_DENIED = 3
    OBJECT_UNDEFINED = 4
    OBJECT_CLASS_INCONSISTENT = 9
    OBJECT_UNAVAILABLE = 11
    TYPE_UNMATCHED = 12
    SCOPE_OF_ACCESS_VIOLATED = 13
    DATA_BLOCK_UNAVAILABLE = 14
    LONG_ACTION_ABORTED = 15
    NO_LONG_ACTION_IN_PROGRESS = 16
    OTHER_REASON = 250
