[mypy]
python_version = 3.9
# 逐步启用 strict，先宽松配置
warn_return_any = True
warn_unused_configs = True
check_untyped_defs = True
no_implicit_optional = True
warn_unused_ignores = True
warn_no_return = True
follow_imports = silent
ignore_missing_imports = True

[[mypy.overrides]]
module = "tests.*"
ignore_errors = true

[[mypy.overrides]]
module = "dlms_cosem.cosem.C*"
ignore_errors = true

[[mypy.plugins]]
name = "mypy_attrs"
